### ISSUE TITLE
ungraceful socket disconnection

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p-swarm#219]
Using js-ipfs, when I disconnect the network this happens:

```
index.js:483 Uncaught Error: underlying socket has been closed
    at index.js:483
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (index.js:480)
    at index.js:43
    at call (index.js:50)
    at Array.forEach (<anonymous>)
    at index.js:70
    at f (once.js:17)
    at Stream.<anonymous> (index.js:29)
    at Stream.f (once.js:25)
```

Once a multiplexer gets destroyed, `dignifiedquire/multiplex` propagates an error to the channel sub-streams [here](https://github.com/dignifiedquire/multiplex/blob/master/src/index.js#L475-L479).

Somewhere in the IPFS stack there seams to be a place where a channel is getting created, but the `error` event is not being handled.

**Comment by pgte** [comment]
I've traced this back to the code that creates the stream, and it seams to emanate from inside the swarm.dial function:

```
at Multiplex.createStream (http://localhost:12345/js/app.js:136448:17)
    at MultiplexMuxer.newStream (http://localhost:12345/js/app.js:139405:33)
    at openConnInMuxedConn (http://localhost:12345/js/app.js:156966:16)
    at gotMuxer (http://localhost:12345/js/app.js:156855:7)
    at Swarm.dial (http://localhost:12345/js/app.js:156823:7)
    at _getPeerInfo (http://localhost:12345/js/app.js:196802:18)
    at setImmediate (http://localhost:12345/js/app.js:196861:24)
    at http://localhost:12345/js/app.js:181532:16
    at onNextTick (http://localhost:12345/js/app.js:210598:12)
    at Item.run (http://localhost:12345/js/app.js:207808:14)
```

**Comment by pgte** [comment]
More specifically, [here](https://github.com/libp2p/js-libp2p-swarm/blob/master/src/dial.js#L74-L76).

I guess that somewhere this code should handle error events in the connection to prevent uncaught exceptions and allow the socket to close gracefully.

In the light of [this comment](https://github.com/libp2p/js-libp2p-multiplex/pull/66#issuecomment-310110761), how should an occurring error be handled?

**Comment by pgte** [comment]
Nevermind, found project-specific dependency that was not propagating error properly. Not libp2p or IPFS at fault here.
