### ISSUE TITLE
 Libp2p init error 

### ISSUE THREAD

**Issue by 18dew** [libp2p/js-libp2p-swarm#84]
While Requiring libp2p-swarm throws out following error - 

> const Swarm = require('libp2p-swarm')
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ <>/Desktop/codebase/git/devp2p/test/node_modules/libp2p-swarm/lib/transport.js:7:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by 18dew** [comment]
Am I missing on any thing or recent changes is causing it, as I see couple of commits happening at backend.

**Comment by diasdavid** [comment]
Ah, we missed to add that dep. Fixing in a sec :)

**Comment by diasdavid** [comment]
done :)
